export const apiBaseUrl = "http://localhost:3003/api";
export const TAGS = [
  "Action",
  "Adventure",
  "Boys' Love",
  "Comedy",
  "Crime",
  "Drama",
  "Fantasy",
  "Girls' Love",
  "Historical",
  "Horror",
  "Isekai",
  "Magical Girls",
  "Mecha",
  "Medical",
  "Mystery",
  "Philosophical",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Superhero",
  "Thriller",
  "Tragedy",
  "Wuxia",
];
export const DEMOGRAPHICS = ["Shoujo", "Shounen", "Josei", "Seinen", "N/A"];
